### ISSUE TITLE
Test directories with Unicode names break install on Windows

### ISSUE THREAD

**Issue by pfmoore** [iElectric/mr.bob#71] opened 2014-10-11 15:28 UTC
If I do ```pip install mr.bob``` with Python 3.4 on I get Unicode decoding errors. This appears to be somehow related to Unicode filename handling. I haven't worked out the details, but I can confirm that removing the directory ```encodingč``` from ```mrbob/tests/templates``` fixes the install problem.

I don't follow the tests well enough to propose a patch, but I would suggest that the test that uses a Unicode directory builds the test files in a temporary location during tests setup, rather than shipping them in the sdist. This would avoid the issue - I have used this approach in the past.

[Later] It's a distutils bug ultimately, the ```--record``` option writes filenames using the system codepage, which is CP1252 on my Windows box, and that doesn't include the filename characters used here.

**Comment by iElectric** [comment] 2015-02-18 11:45
Closing as duplicate of #70

**Closed by iElectric** 2015-02-18 11:45 UTC
